#!/bin/sh

mkdir -p src/protogen

$(npm bin)/grpc_tools_node_protoc \
    --proto_path=src/protobuf \
    --plugin=$(npm bin)/protoc-gen-ts_proto \
    --ts_proto_out=src/protogen \
    --ts_proto_opt=outputServices=grpc-js \
    --ts_proto_opt=nestJs=true \
    --ts_proto_opt=esModuleInterop=true \
    --ts_proto_opt=addGrpcMetadata=true \
    --ts_proto_opt=oneof=unions \
    src/protobuf/*.proto
